import Link from 'next/link'
import LegalDocument from '@/components/legal-document'
export const metadata={title:'Conditions générales de vente — CashLance'}
export default function Page(){return <LegalDocument title="Conditions générales de vente (CGV)">
<p>Projet contractuel applicable aux offres professionnelles CashLance, à faire valider et compléter avant toute acceptation contractuelle.</p>
<h2>1. Parties et champ d'application</h2><p>Le fournisseur est [IDENTITÉ DE L'ÉDITEUR À COMPLÉTER], exploitant CashLance. Le Client est la personne physique ou morale qui souscrit dans le cadre de son activité professionnelle, représentée par un utilisateur autorisé. Les règles impératives éventuellement applicables aux petits professionnels ou consommateurs prévalent sur toute disposition contraire.</p>
<h2>2. Service souscrit</h2><p>CashLance fournit un accès en ligne à un outil d'import de créances, d'extraction assistée par IA pour PDF/images, de vérification des informations, de programmation de relances et de suivi de leur historique. L'abonnement n'inclut pas la garantie de règlement d'une facture, une activité de recouvrement judiciaire ou la certification de données comptables.</p>
<h2>3. Offres et prix</h2><p>Les offres affichées sont Solo (19 € HT par mois ; 20 factures actives), Pro (39 € HT par mois ; 100 factures actives) et Équipe (79 € HT par mois ; factures actives illimitées, jusqu'à cinq utilisateurs), sous réserve des caractéristiques présentées au moment de la commande. TVA ou mention fiscale applicable : [À CONFIRMER AVEC LA SITUATION RÉELLE DE L'ÉDITEUR]. Aucun prix TTC ne peut être garanti par ce projet tant que la situation fiscale n'est pas validée.</p>
<h2>4. Essai et souscription</h2><p>Un essai de 14 jours est prévu pour une première souscription éligible. Les informations de prix et la date du premier paiement doivent être présentées au Client dans Stripe Checkout avant validation. L'inscription initiale ne requiert pas de carte bancaire. Les modalités effectives de prélèvement dépendent du récapitulatif de commande accepté et de la configuration Stripe.</p>
<h2>5. Paiement et renouvellement</h2><p>Les abonnements sont mensuels, facturés selon l'échéancier confirmé lors de la souscription. Les moyens de paiement et taxes effectivement appliqués sont indiqués à l'étape de paiement. Tout incident de paiement peut entraîner une limitation ou suspension de l'accès après information du Client dans les conditions légales applicables. Les modalités des pénalités B2B éventuelles et de l'indemnité forfaitaire de recouvrement doivent être validées et précisées sur les documents de facturation : [À COMPLÉTER].</p>
<h2>6. Résiliation</h2><p>Le Client peut demander la résiliation depuis son espace de facturation via le portail Stripe, selon les modalités visibles à la souscription. Les effets de la résiliation et l'accès aux données jusqu'à la fin de période doivent être alignés avec la configuration effective de Stripe et documentés : [DÉLAI ET SORT DES DONNÉES À CONFIRMER]. Une suspension ne dispense pas du paiement des sommes légalement dues avant sa date d'effet.</p>
<h2>7. Obligations du Client</h2><p>Le Client garantit être autorisé à traiter les factures et coordonnées transmises, vérifier le destinataire, le solde et l'échéance, actualiser les règlements, n'utiliser les relances que pour des créances licites et ne pas envoyer de messages trompeurs, abusifs ou harcelants. Les informations proposées par l'IA ne constituent ni une preuve de dette ni un avis juridique.</p>
<h2>8. Disponibilité et assistance</h2><p>Le service dépend notamment de l'accès internet et de prestataires techniques. Les plages de maintenance, canal d'assistance et éventuels engagements de niveau de service seront précisés dans la version définitive : [À COMPLÉTER]. Aucun taux de disponibilité contractuel n'est promis par ce projet.</p>
<h2>9. Responsabilités et incidents</h2><p>Chaque partie répond des dommages selon les dispositions légales et les stipulations valablement convenues. L'éditeur ne garantit ni les performances du débiteur, ni la livraison de chaque e-mail, ni le recouvrement. Aucune clause du présent projet n'a pour objet d'écarter une responsabilité qui ne peut légalement être exclue. Toute éventuelle limitation chiffrée de responsabilité nécessite une validation juridique spécifique.</p>
<h2>10. Données personnelles et sous-traitance</h2><p>Le traitement des données est expliqué dans la <Link href="/confidentialite">politique de confidentialité</Link>. Un accord de sous-traitance conforme à l'article 28 du RGPD devra être mis à disposition des Clients lorsqu'ils agissent comme responsables de traitement pour leurs débiteurs : [DOCUMENT DPA À FINALISER].</p>
<h2>11. Rétractation et règlement des différends</h2><p>Le service vise les professionnels. Les droits impératifs de rétractation éventuellement applicables à une catégorie particulière de cocontractants ne sont pas exclus. Les modalités de réclamation, médiation lorsqu'elle est légalement requise, droit applicable et juridiction compétente doivent être définies selon la clientèle réellement acceptée : [À COMPLÉTER].</p>
<h2>12. Version et contact</h2><p>Le texte contractuel accepté devra être conservé avec sa version et sa date. Contact de l'éditeur : [À COMPLÉTER].</p>
</LegalDocument>}
