import {test,expect,Page} from '@playwright/test'
import path from 'node:path'
const fixture=(name:string)=>path.resolve('tests/fixtures',name)
async function signup(page:Page){
  await page.goto('/?utm_source=meta&utm_campaign=import-test')
  await page.getByRole('link',{name:'Essayer gratuitement pendant 14 jours'}).first().click()
  await page.locator('input').nth(0).fill('Entreprise test')
  await page.getByPlaceholder('vous@entreprise.fr').fill('test@example.invalid')
  await page.getByPlaceholder('8 caractères minimum').fill('local-test-password')
  await page.getByRole('button',{name:'Commencer mes 14 jours gratuits'}).click()
  await expect(page.getByRole('heading',{name:'Comment voulez-vous découvrir CashLance ?'})).toBeVisible()
}
async function noOverflow(page:Page){expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)}
async function validate(page:Page){
  for(const checkbox of await page.getByRole('checkbox',{name:/J’ai vérifié/}).all())await checkbox.check()
  await page.getByRole('checkbox',{name:/Je confirme les informations/}).check()
  await page.getByRole('button',{name:/Valider les/}).click()
  await expect(page.getByRole('heading',{name:/relance est programmée/})).toBeVisible()
}
test.beforeEach(async({page,request})=>{
  await request.post('http://127.0.0.1:54440/reset')
  await page.route('**/*',route=>{const u=new URL(route.request().url());return ['127.0.0.1','localhost'].includes(u.hostname)||['blob:','data:'].includes(u.protocol)?route.continue():route.abort()})
})
test('mobile: signup with attribution, safe demo, then real CSV import',async({page,request})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
  await signup(page);await noOverflow(page)
  await page.getByRole('button',{name:'Tester avec un exemple'}).click()
  await page.getByRole('button',{name:'Simuler la programmation'}).click()
  await expect(page.getByText(/Votre démonstration est prête/)).toBeVisible()
  expect((await (await request.get('http://127.0.0.1:54440/inspect')).json()).invoices).toHaveLength(0)
  await page.getByRole('button',{name:'Supprimer la démonstration'}).click()
  await page.getByRole('link',{name:'Importer mes documents'}).click()
  await expect(page.locator('#documents')).toBeEnabled()
  await page.locator('#documents').setInputFiles({name:'export.csv',mimeType:'text/csv',buffer:Buffer.from('TIERS;NUM_PIECE;ECHEANCE;SOLDE;EMAIL_TIERS;DEVISE\nMartin SARL;FA254;15/09/2026;840;client@example.invalid;EUR')})
  await page.getByRole('button',{name:'Vérifier ces créances'}).click()
  await expect(page.getByRole('button',{name:/Valider les/})).toBeDisabled()
  await noOverflow(page);await validate(page)
  const state=await(await request.get('http://127.0.0.1:54440/inspect')).json()
  expect(state.metadata.attribution.utm_source).toBe('meta');expect(state.invoices).toHaveLength(1)
  await page.getByRole('link',{name:'Voir mon tableau de bord'}).click();await expect(page.getByRole('heading',{name:'Martin SARL'})).toBeVisible();await noOverflow(page)
  await page.screenshot({path:'test-results/mobile-dashboard.png',fullPage:true})
  expect(errors).toEqual([])
})
test('PDF batch: extraction, debtor confirmation and scheduling',async({page})=>{
  await signup(page);await page.getByRole('link',{name:'Importer mes documents'}).click()
  await expect(page.locator('#documents')).toBeEnabled()
  await page.locator('#documents').setInputFiles([fixture('invoice.pdf'),fixture('invoice2.pdf')])
  await expect(page.getByRole('heading',{name:/Client à relancer identifié/})).toHaveCount(2)
  await expect(page.getByLabel('Client / raison sociale').first()).toHaveValue('MARTIN SARL')
  await expect(page.getByLabel('Email du client').first()).toHaveValue('compta@example.invalid')
  await validate(page)
})
test('XLSX: mapping, missing email, saved draft and later activation',async({page})=>{
  await signup(page);await page.getByRole('link',{name:'Importer mes documents'}).click()
  await expect(page.locator('#documents')).toBeEnabled()
  await page.locator('#documents').setInputFiles(fixture('invoices.xlsx'))
  await page.getByRole('button',{name:'Vérifier ces créances'}).click()
  await expect(page.getByText('Email requis pour les relances',{exact:true})).toBeVisible()
  await page.getByRole('checkbox',{name:'Programmer les relances après validation'}).uncheck()
  await page.getByRole('checkbox',{name:/J’ai vérifié/}).check()
  await page.getByRole('checkbox',{name:/Je confirme les informations/}).check()
  await page.getByRole('button',{name:/Valider les/}).click()
  await expect(page.getByRole('heading',{name:'Vos créances sont enregistrées'})).toBeVisible()
  await page.getByRole('link',{name:'Voir mon tableau de bord'}).click()
  await page.getByText('Programmer les relances',{exact:true}).click()
  await page.getByLabel('Email du client',{exact:true}).fill('late@example.invalid')
  await page.getByRole('checkbox',{name:/Je confirme le client/}).check()
  await page.getByRole('button',{name:'Confirmer et programmer'}).click()
  await expect(page.getByText('En relance',{exact:true})).toBeVisible()
})
for(const format of ['png','jpg']) test(`photo ${format}: OCR local and editable extracted information`,async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
  await signup(page);await page.getByRole('link',{name:'Importer mes documents'}).click()
  await expect(page.locator('#documents')).toBeEnabled()
  await page.locator('#documents').setInputFiles(fixture(`invoice.${format}`))
  await expect(page.getByLabel('Client / raison sociale')).toHaveValue(/MARTIN/, {timeout:90000})
  await expect(page.getByLabel('Restant dû')).toHaveValue('1280,00')
  await page.getByLabel('Email du client').fill('compta@example.invalid')
  await noOverflow(page);await validate(page);expect(errors).toEqual([])
})
test('desktop landing and mobile pricing have no horizontal overflow',async({page})=>{
  await page.setViewportSize({width:1440,height:900});await page.goto('/');await noOverflow(page)
  await page.screenshot({path:'test-results/desktop-landing.png',fullPage:true})
  await page.setViewportSize({width:390,height:844});await page.goto('/pricing');await noOverflow(page)
  await page.goto('/import');await expect(page).toHaveURL(/login/)
})
