import {test,expect} from '@playwright/test'
test('dashboard release: dates, filters, persisted theme/view and confirmed payment at mobile/desktop widths',async({page,request})=>{
 await request.post('http://127.0.0.1:54440/reset')
 await page.route('**/*',r=>['127.0.0.1','localhost'].includes(new URL(r.request().url()).hostname)?r.continue():r.abort())
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 await page.goto('/')
 await page.getByRole('link',{name:'Essayer gratuitement pendant 14 jours'}).first().click()
 await page.getByPlaceholder('Nom de votre entreprise').fill('Entreprise test')
 await page.getByPlaceholder('vous@entreprise.fr').fill('test@example.invalid')
 await page.getByPlaceholder('8 caractères minimum').fill('local-test-password')
 await page.getByRole('button',{name:'Commencer mes 14 jours gratuits'}).click()
 await expect(page).toHaveURL(/\/pricing$/)
 await request.post('http://127.0.0.1:54440/subscription',{data:{status:'trialing'}})
 await request.post('http://127.0.0.1:54440/rest/v1/rpc/confirm_import_server',{data:{schedule:false,rows:[{confirmed:true,currency:'EUR',client:'Client synthétique',email:'client@example.invalid',invoiceNumber:'RELEASE-001',amount_cents:10000,due:'2026-10-15',details:{invoiceDate:'2026-10-01'}}]}})
 await page.goto('/dashboard')
 await expect(page.getByText('Date facture : 01/10/2026')).toBeVisible()
 await page.getByRole('button',{name:'Activer le mode clair'}).click()
 await page.getByRole('button',{name:'☷ Liste'}).click()
 await page.getByRole('searchbox').fill('RELEASE-001')
 await page.getByRole('button',{name:/À programmer/}).click()
 await page.getByRole('button',{name:'▦ Cartes'}).click()
 await expect(page.getByRole('searchbox')).toHaveValue('RELEASE-001')
 await expect(page.getByRole('button',{name:/À programmer/})).toHaveClass(/active/)
 await page.getByRole('button',{name:'☷ Liste'}).click()
 await page.reload()
 await expect(page.locator('html')).toHaveAttribute('data-theme','light')
 await expect(page.getByRole('button',{name:'☷ Liste'})).toHaveAttribute('aria-pressed','true')
 for(const width of [390,412,1280]){
  await page.setViewportSize({width,height:844})
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 }
 await page.getByRole('button',{name:'✓ Facture payée'}).click()
 expect((await(await request.get('http://127.0.0.1:54440/inspect')).json()).invoices[0].status).toBe('open')
 await page.getByRole('button',{name:'Confirmer',exact:true}).click()
 await expect(page.getByText('Facture réglée').first()).toBeVisible()
 expect((await(await request.get('http://127.0.0.1:54440/inspect')).json()).invoices[0].status).toBe('paid')
 expect(errors).toEqual([])
})
