import { afterEach, beforeEach, expect, it, vi } from 'vitest'
const m = vi.hoisted(() => ({ construct: vi.fn(), retrieve: vi.fn(), rpc: vi.fn() }))
vi.mock('@/lib/stripe', async original => ({ ...await original<typeof import('../lib/stripe')>(), getStripe: () => ({ webhooks: { constructEvent: m.construct }, subscriptions: { retrieve: m.retrieve } }) }))
vi.mock('@/lib/supabase/admin', () => ({ createAdminClient: () => ({ rpc: m.rpc }) }))
import { POST } from '../app/api/stripe/webhook/route'
const sub = (status = 'trialing') => ({ id: 'sub_test', created: 123, customer: { id: 'cus_test' }, status, metadata: { plan: 'solo', organization_id: 'org_test' }, items: { data: [{ price: { id: 'price_team_test' } }] } })
const event = (type: string, object: object) => m.construct.mockReturnValue({ id: 'evt_test', type, data: { object } })
const request = (signature = true) => new Request('https://cashlance.fretixo.fr/api/stripe/webhook', { method: 'POST', body: '{}', headers: signature ? { 'stripe-signature': 'fake' } : {} })
beforeEach(() => {
  vi.stubEnv('STRIPE_SECRET_KEY', 'test-placeholder'); vi.stubEnv('STRIPE_WEBHOOK_SECRET', 'test-placeholder'); vi.stubEnv('STRIPE_PRICE_TEAM', 'price_team_test')
  m.retrieve.mockResolvedValue(sub()); m.rpc.mockResolvedValue({ data: { subscription_status: 'trialing', stripe_subscription_id: 'sub_test' }, error: null })
})
afterEach(() => vi.unstubAllEnvs())
it('rejects missing/invalid signatures before Stripe retrieval and database access', async () => {
  expect((await POST(request(false))).status).toBe(400)
  m.construct.mockImplementationOnce(() => { throw Error('invalid') })
  expect((await POST(request())).status).toBe(400)
  expect(m.retrieve).not.toHaveBeenCalled(); expect(m.rpc).not.toHaveBeenCalled()
})
it.each(['active','trialing','past_due','canceled'])('retrieves current %s state before atomic synchronization', async status => {
  m.retrieve.mockResolvedValue(sub(status))
  event('checkout.session.completed', { mode: 'subscription', subscription: { id: 'sub_test' }, client_reference_id: 'org_test' })
  expect((await POST(request())).status).toBe(200)
  expect(m.retrieve).toHaveBeenCalledWith('sub_test')
  expect(m.rpc).toHaveBeenCalledWith('sync_stripe_subscription', expect.objectContaining({ p_event: 'evt_test', p_created: 123, p_status: status === 'canceled' ? 'cancelled' : status, p_plan: 'team', p_customer: 'cus_test' }))
})
it.each(['customer.subscription.created','customer.subscription.updated','customer.subscription.deleted'])('handles %s via current state, not stale payload', async type => {
  event(type, sub('active'))
  expect((await POST(request())).status).toBe(200)
  expect(m.rpc.mock.calls[0][1].p_status).toBe('trialing')
})
it.each(['invoice.paid','invoice.payment_failed'])('does not invent status from %s or a zero-value invoice', async type => {
  event(type, { amount_paid: 0, parent: { subscription_details: { subscription: 'sub_test' } } })
  expect((await POST(request())).status).toBe(200)
  expect(m.rpc.mock.calls[0][1].p_status).toBe('trialing')
})
it('does not activate one-off invoices or incomplete Checkout payloads', async () => {
  event('invoice.paid', { customer: 'cus_test', amount_paid: 100 })
  expect((await POST(request())).status).toBe(200)
  event('checkout.session.completed', { mode: 'subscription', customer: 'cus_test' })
  expect((await POST(request())).status).toBe(200)
  expect(m.rpc).not.toHaveBeenCalled()
})
it('requests Stripe retry after failed synchronization', async () => {
  event('customer.subscription.updated', sub())
  m.rpc.mockResolvedValueOnce({ data: null, error: { message: 'private' } })
  expect((await POST(request())).status).toBe(500)
  m.retrieve.mockRejectedValueOnce(Error('private'))
  expect((await POST(request())).status).toBe(500)
})
