import Link from 'next/link'
import FunnelTracker from '@/components/funnel-tracker'
export default function Home(){return <main className="wrap">
  <div className="nav"><div><a className="ecosystem" href="https://fretixo.fr">← FRETIXO</a><div className="brand">Cash<b>lance</b></div></div><Link className="btn alt" href="/login">Connexion</Link></div>
  <FunnelTracker /><section className="hero"><div><span className="badge">Vos relances, simplement</span><h1>Déposez vos factures. CashLance prépare vos relances.</h1><p className="lead">Importez vos factures ou votre fichier comptable. CashLance récupère les clients, montants et échéances puis prépare vos relances.</p><p className="actions"><Link className="btn" href="/login?mode=signup" data-trial-cta>Essayer gratuitement pendant 14 jours</Link></p><p className="muted">Sans carte bancaire à l’inscription. Pas de document sous la main ? Testez avec un exemple.</p></div>
  <div className="panel"><span className="badge">Exemple fictif</span><h2>Votre facture devient une action</h2><div className="row"><span>Document importé</span><strong>DEMO-001.pdf</strong></div><div className="row"><span>Client à vérifier</span><strong>Entreprise Démo SARL</strong></div><div className="row"><span>Montant détecté</span><strong>1 280 €</strong></div><div className="row"><span>Après votre validation</span><span className="status">Relance programmée ✓</span></div><p className="muted">Vous vérifiez. CashLance prépare la suite.</p></div></section>
  <section className="section"><h2>Trois étapes pour retrouver du temps</h2><div className="grid3"><div className="card"><h3>1. Importez vos documents</h3><p>Une facture, plusieurs photos ou un export comptable.</p></div><div className="card"><h3>2. Vérifiez les informations détectées</h3><p>Corrigez le client, le montant et l’échéance. Complétez seulement ce qui manque.</p></div><div className="card"><h3>3. Activez vos relances</h3><p>Choisissez votre scénario et confirmez. Aucun envoi sans validation.</p></div></div></section>
  <section className="section"><h2>Vos documents habituels</h2><p className="lead">PDF · JPG · PNG · Excel XLSX · CSV</p><p className="muted">Import en masse, colonnes pré-associées et corrections possibles. Les PDF et images sont analysés avec OpenAI ; une photo nette améliore la détection. Pour un grand livre complexe, privilégiez Excel ou CSV.</p><div className="grid3"><div className="card"><h3>Moins de saisie</h3><p>Clients et factures sont créés ensemble après votre vérification.</p></div><div className="card"><h3>Un suivi centralisé</h3><p>Retrouvez vos créances, réponses et relances dans un seul espace.</p></div><div className="card"><h3>Vous gardez la main</h3><p>Vérifiez chaque destinataire et chaque échéance avant de programmer.</p></div></div></section>
  <section className="section"><h2>14 jours pour essayer</h2><p>Solo 19 €/mois · Pro 39 €/mois · Team 79 €/mois.</p><Link className="btn alt" href="/pricing">Comparer les offres</Link></section>
  <section className="section"><h2>Vos questions</h2><details><summary>Je n’ai pas de facture avec moi.</summary><p>Créez votre compte et testez un exemple fictif. Vous pourrez importer vos documents plus tard.</p></details><details><summary>Que se passe-t-il si une information manque ?</summary><p>Vous la complétez dans l’écran de vérification. L’email est indispensable pour programmer les relances, mais pas pour enregistrer une créance.</p></details><details><summary>Un email part-il dès l’import ?</summary><p>Non. Vous devez vérifier les informations et confirmer le scénario.</p></details><details><summary>Mes fichiers sont-ils publics ?</summary><p>Non. Les PDF et images sont transmis à OpenAI pour analyse, sans conservation du fichier original par CashLance. Excel et CSV sont lus sur votre appareil. Les informations extraites restent dans votre espace privé.</p></details></section>
  <section className="section"><h2>Préparez votre première relance.</h2><Link className="btn" href="/login?mode=signup" data-trial-cta>Essayer gratuitement pendant 14 jours</Link></section>
</main>}
