import Link from 'next/link'
import LegalDocument from '@/components/legal-document'
export const metadata={title:'Confidentialité et données personnelles — CashLance'}
export default function Page(){return <LegalDocument title="Politique de confidentialité et de protection des données">
<p><strong>À compléter avant lancement :</strong> identité et coordonnées du responsable de traitement, contact RGPD, durées de conservation exactes, pays d'hébergement et transferts internationaux vérifiés dans les contrats des prestataires.</p>
<h2>1. Rôles et catégories de personnes</h2><p>Pour la gestion des comptes, de l'abonnement, de la sécurité et de la relation commerciale, l'éditeur [IDENTITÉ À COMPLÉTER] agit en principe comme responsable de traitement. Pour les données relatives aux débiteurs et factures importées pour le compte d'une entreprise cliente, celle-ci détermine les finalités et l'éditeur agit en principe comme sous-traitant, selon un accord RGPD à formaliser.</p>
<h2>2. Données traitées</h2><p>Selon l'usage : identité professionnelle, e-mail, organisation, références des factures, noms et coordonnées des débiteurs, montants, échéances, états de relance, réponses reçues, journaux techniques et données d'abonnement nécessaires au paiement. L'éditeur ne doit pas demander de catégories particulières de données personnelles sans nécessité explicite.</p>
<h2>3. Finalités et bases juridiques</h2><p>Création et gestion du compte, exécution du service et de l'abonnement, sécurité, respect des obligations comptables et légales, assistance et suivi commercial sollicité. Les bases juridiques (exécution contractuelle, obligations légales, intérêt légitime et consentement lorsqu'il est requis) doivent être associées précisément à chaque finalité dans le registre de traitements de l'éditeur.</p>
<h2>4. Extraction avec OpenAI</h2><p>Lorsque l'utilisateur demande l'analyse d'un PDF ou d'une image, le document est transmis à l'API OpenAI pour proposer les informations d'une facture. Le code utilise le paramètre API <code>store:false</code>. Cette option n'est pas une garantie d'absence de toute conservation technique par le prestataire ; ses conditions de traitement, durées éventuelles et transferts doivent être vérifiés contractuellement. CashLance ne conserve pas le fichier original pendant ce traitement d'analyse ; les champs extraits peuvent être enregistrés dans l'espace privé et dans un cache temporaire. L'analyse facultative des réponses par OpenAI est distincte et désactivée tant qu'elle n'est pas activée expressément.</p>
<h2>5. Prestataires</h2><p>Le fonctionnement fait notamment appel à Supabase (authentification et base de données), Vercel (hébergement de l'application), Resend (messages électroniques), Stripe (facturation et paiement) et OpenAI (analyse documentaire). Leurs rôles, lieux de traitement, transferts et garanties contractuelles doivent figurer dans le registre et l'accord de sous-traitance avant publication.</p>
<h2>6. Conservation</h2><p>Les données sont conservées le temps nécessaire au service puis selon les obligations légales et contractuelles. Une analyse identique peut être mise en cache de manière temporaire afin d'éviter des appels API répétés. Tableau exact des durées pour les comptes, créances, messages, événements, facturation, journaux et sauvegardes : [À COMPLÉTER ET VÉRIFIER DANS LE CODE ET LES CONTRATS].</p>
<h2>7. Destinataires et sécurité</h2><p>L'accès est limité aux utilisateurs autorisés de l'organisation et aux prestataires nécessaires à la prestation, selon leurs droits respectifs. Les mesures techniques comprennent notamment des contrôles d'accès et une vérification des événements entrants, sans garantie absolue contre tout incident.</p>
<h2>8. Vos droits</h2><p>Selon votre situation et les limites légales, vous pouvez solliciter l'accès, la rectification, l'effacement, la limitation, la portabilité et l'opposition, ainsi que retirer un consentement lorsque celui-ci sert de base au traitement. Pour les données des débiteurs importées par un Client, adressez-vous en premier lieu à cette entreprise responsable du traitement. Contact RGPD CashLance : [À COMPLÉTER]. Vous pouvez aussi déposer une réclamation auprès de la CNIL (cnil.fr).</p>
<h2>9. Traceurs</h2><p>Consultez la <Link href="/cookies">politique des cookies</Link>. Les cookies non essentiels ne doivent pas être déclenchés avant le recueil du consentement lorsqu'il est requis.</p>
<h2>10. Modifications</h2><p>Les évolutions significatives de cette politique seront datées et portées à la connaissance des utilisateurs selon les exigences applicables.</p>
</LegalDocument>}
